### ISSUE TITLE
Logging/rollback plugin

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#10]
Should install a logging and rollback plugin, to isolate cheating and rollback from glitches.

**Comment by mushroomhostage** [comment]
[HawkEye](http://dev.bukkit.org/server-mods/hawkeye/) looks like a good choice. There is also the up-and-coming [CoreProtect](http://www.reddit.com/r/admincraft/comments/qjm0q/coreprotect_official_details/).

HawkEye requires the MySQL database to be setup.

**Comment by mushroomhostage** [comment]
sudo apt-get install mysql-server

**Comment by mushroomhostage** [comment]
Installed [HawkEye 1.0.6b](http://dev.bukkit.org/server-mods/hawkeye/files/11-hawk-eye-v1-0-6b/), setup MySQL database, up and running. Events are being logged to the hawkeye table (total so far: 3627), but, there are errors on the console.

Whenever I open a chest:

```
 03:12:34 [SEVERE] Could not pass event org.bukkit.event.player.PlayerInteractEvent to HawkEye org.bukkit.event.EventException
    at uk.co.oliwali.HawkEye.listeners.HawkEyeListener$1.execute(HawkEyeListener.java:57)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:460)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:187)
    at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:310)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:616)
    at net.minecraft.server.Packet15Place.handle(SourceFile:39)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:231)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:101)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:543)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
 Caused by: java.lang.NoClassDefFoundError: org/bukkit/inventory/InventoryHolder
    at uk.co.oliwali.HawkEye.ContainerAccessManager.checkInventoryOpen(ContainerAccessManager.java:53)
    at uk.co.oliwali.HawkEye.listeners.MonitorPlayerListener.onPlayerInteract(MonitorPlayerListener.java:110)
    at sun.reflect.GeneratedMethodAccessor154.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at uk.co.oliwali.HawkEye.listeners.HawkEyeListener$1.execute(HawkEyeListener.java:55)
    ... 12 more
```

Whenever something dies (monster):

```
 03:12:02 [SEVERE] Could not pass event org.bukkit.event.entity.EntityDeathEvent to HawkEye org.bukkit.event.EventException
    at uk.co.oliwali.HawkEye.listeners.HawkEyeListener$1.execute(HawkEyeListener.java:57)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:460)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:352)
    at net.minecraft.server.EntityLiving.dropDeathLoot(EntityLiving.java:675)
    at net.minecraft.server.EntityLiving.die(EntityLiving.java:650)
    at net.minecraft.server.EntityLiving.damageEntity(EntityLiving.java:546)
    at net.minecraft.server.EntityMonster.damageEntity(EntityMonster.java:44)
    at net.minecraft.server.Entity.am(Entity.java:291)
    at net.minecraft.server.EntityLiving.am(EntityLiving.java:172)
    at net.minecraft.server.Entity.y_(Entity.java:211)
    at net.minecraft.server.EntityLiving.y_(EntityLiving.java:329)
    at net.minecraft.server.EntityMonster.y_(EntityMonster.java:31)
    at net.minecraft.server.World.entityJoinedWorld(World.java:1273)
    at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:110)
    at net.minecraft.server.World.playerJoinedWorld(World.java:1255)
    at net.minecraft.server.World.tickEntities(World.java:1156)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:534)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
 Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.EntityDeathEvent.getEntity()Lorg/bukkit/entity/LivingEntity;
    at uk.co.oliwali.HawkEye.listeners.MonitorEntityListener.onEntityDeath(MonitorEntityListener.java:50)
    at sun.reflect.GeneratedMethodAccessor187.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at uk.co.oliwali.HawkEye.listeners.HawkEyeListener$1.execute(HawkEyeListener.java:55)
    ... 19 more
```

Is HawkEye 1.0.6b compatible with CraftBukkit 1.1-R4? BukkitDev says its for 1.1-R7, and the previous release 1.0.5b was for "1.0.0" on Dec 15th, 2011.

**Comment by mushroomhostage** [comment]
Got a new error, also has problems with Enderman pickup events:

```
14:01:05 [SEVERE] Could not pass event org.bukkit.event.entity.EntityChangeBlockEvent to HawkEye
org.bukkit.event.EventException
    at uk.co.oliwali.HawkEye.listeners.HawkEyeListener$1.execute(HawkEyeListener.java:57)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:460)
    at net.minecraft.server.EntityEnderman.d(EntityEnderman.java:117)
    at net.minecraft.server.EntityLiving.y_(EntityLiving.java:341)
    at net.minecraft.server.EntityMonster.y_(EntityMonster.java:31)
    at net.minecraft.server.World.entityJoinedWorld(World.java:1273)
    at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:110)
    at net.minecraft.server.World.playerJoinedWorld(World.java:1255)
    at net.minecraft.server.World.tickEntities(World.java:1156)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:534)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.EntityChangeBlockEvent.getEntity()Lorg/bukkit/entity/LivingEntity;
    at uk.co.oliwali.HawkEye.listeners.MonitorEntityListener.onEntityChangeBlock(MonitorEntityListener.java:112)
    at sun.reflect.GeneratedMethodAccessor267.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at uk.co.oliwali.HawkEye.listeners.HawkEyeListener$1.execute(HawkEyeListener.java:55)
    ... 12 more
```

**Comment by mushroomhostage** [comment]
Yep, it was a version incompatibility.

[HawkEye 1.0.5b](http://dev.bukkit.org/server-mods/hawkeye/files/9-hawk-eye-v1-0-5b/) installed, works great at least as far as I've tested.
