### ISSUE TITLE
QuickBench not crafting with UU-matter

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#102]
Since updating to IC2 v1.103 (in exphc1.2.5rev6), the QuickBench no longer shows crafting outputs for UU-matter. Seems to work with other IC2 recipes, just not matter.

**Comment by mushroomhostage** [comment]
```
11:50:05 [INFO] - testing class=ic2.common.AdvRecipe w=0 outputMatch=ItemStack 16x1:0 (STONE) tag=null inputs=[Lorg.bukkit.inventory.ItemStack;@66adec54 vs ingredientsList=[null, null, null, null, [ItemStack{X30188 x 1}], null, null, null, null]
11:50:05 [INFO]   ~ taking ItemStack 1x30188:0 (X30188) tag=null takenItem=ItemStack 1x30188:0 (X30188) tag=null
11:50:05 [INFO]  + craftable with [Lorg.bukkit.inventory.ItemStack;@66adec54
11:50:05 [INFO]  + recipe size 9 = 0x2147483647
11:50:05 [INFO] precraft skipping recipe: ic2.common.AdvRecipe@2f55a0 because: java.lang.ArithmeticException: / by zero
11:50:05 [SEVERE] java.lang.ArithmeticException: / by zero
11:50:05 [SEVERE]   at com.exphc.QuickBench.TransparentRecipe.canCraft(QuickBench.java:368)
11:50:05 [SEVERE]   at com.exphc.QuickBench.TransparentRecipe.precraft(QuickBench.java:522)
11:50:05 [SEVERE]   at com.exphc.QuickBench.QuickBenchListener.onPlayerInteract(QuickBench.java:661)
11:50:05 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:50:05 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
11:50:05 [SEVERE]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:50:05 [SEVERE]   at java.lang.reflect.Method.invoke(Method.java:601)
11:50:05 [SEVERE]   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
11:50:05 [SEVERE]   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
11:50:05 [SEVERE]   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
11:50:05 [SEVERE]   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467)
11:50:05 [SEVERE]   at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
11:50:05 [SEVERE]   at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:292)
11:50:05 [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:635)
11:50:05 [SEVERE]   at net.minecraft.server.Packet15Place.handle(SourceFile:39)
11:50:05 [SEVERE]   at net.minecraft.server.NetworkManager.b(NetworkManager.java:251)
11:50:05 [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:106)
11:50:05 [SEVERE]   at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:82)
11:50:05 [SEVERE]   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:569)
11:50:05 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
11:50:05 [SEVERE]   at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
```

**Comment by mushroomhostage** [comment]
https://github.com/mushroomhostage/QuickBench/commit/ead75e1e80a2cb35ca96d620f65b3618ccb94b4b Update for IC2 v1.103 - add zero-width recipe check

QuickBench 3.0.3

**Comment by mushroomhostage** [comment]
Fixed
