### ISSUE TITLE
Update Trees++ integration for Thermal Expansion 1.0.4.3

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#103]
https://github.com/mushroomhostage/exphc/issues/75 Thermal Expansion sawmill should be able to cut Trees++ logs
added new recipes to TX 1.0.4.1. in ExphcTweaks https://github.com/mushroomhostage/ExphcTweaks

However this broke with TX 1.0.4.3 since I was accessing private methods. There is now an API that can be used.

**Comment by mushroomhostage** [comment]
```
11:01:36 [SEVERE] Error occurred while enabling ExphcTweaks v1.2.5rev5c (Is it up to date?)
java.lang.NoClassDefFoundError: cofh/thermalexpansion/core/RecipeManager
    at me.exphc.ExphcTweaks.ExphcTweaks.onEnable(ExphcTweaks.java:124)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:386)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:264)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:246)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:377)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:364)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:198)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:428)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.ClassNotFoundException: cofh.thermalexpansion.core.RecipeManager
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 11 more
```

**Comment by mushroomhostage** [comment]
https://github.com/mushroomhostage/ExphcTweaks/commit/25e1f5dca8e4a4bad63657102121ad582e651a5a Thermal Expansion / Trees++: update to 1.0.4.3 TE recipe API

untested

**Comment by mushroomhostage** [comment]
Tested, works fine. Deployed, will take effect after next server restart. ExphcTweaks 1.2.5rev6

**Comment by mushroomhostage** [comment]
Fixed
