### ISSUE TITLE
Random spawn circumvention - near origin?

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#18]
Some players are being spawned suspiciously close to the origin. This shouldn't happen - supposed to be random :)

**Comment by mushroomhostage** [comment]
I suspect this may have to do with logging out on the initial spawn, while you're still in the sky and falling. Senri0 did this and I teleported to him and he spawned very near the origin. Logging out while in the sky can be a common reaction since it looks like something is wrong..you're not normally supposed to be that high. Need to investigate.

**Comment by mushroomhostage** [comment]
ExpHC is currently running RandomSpawn-1.6.3.jar (though /version RandomSpawn says 1.6.1 and the [download link](http://dev.bukkit.org/server-mods/random-spawn/files/16-random-spawn-version-1-6-3b/) said 1.6.3b) for 1.1-R3.

Latest version at the time of this writing is [Random Spawn 1.7](http://dev.bukkit.org/server-mods/random-spawn/files/17-random-spawn-version-1-7/) but it is for 1.1-R7, and ExpHC is on 1.1-R4 and the Bukkit APIs changed so it isn't backwards-compatible. Source is at https://github.com/Josvth/Random-Spawn if I want to backport, but..

**Comment by mushroomhostage** [comment]
There is an exception when players logout while spawn was loading..log from another player:

```
14:41:42 [INFO] Ev.. [] logged in with entity id 108107 at ([world] 183.5, 65.62000000476837, 6.5)
14:41:42 [INFO] [RandomSpawn] (DEBUG): Ev..'s first join in world
14:41:42 [INFO] [RandomSpawn] (DEBUG): Ev.. is teleported somewhere in the sky.
14:41:42 [INFO] [RandomSpawn] (DEBUG): Task NOID: Ev.. is added to the deadlist.
14:41:42 [INFO] [RandomSpawn] (DEBUG): Task NOID: Viewdistance: 10 Chunks per run: 32
14:41:42 [INFO] [RandomSpawn] (DEBUG): Task NOID: Initialisation done! (0ms)
14:41:42 [INFO] [RandomSpawn] (DEBUG): Has gotten an id!
14:41:42 [INFO] [RandomSpawn] (DEBUG): DisconnectListener: Ev.. disconnected while spawn was loading. 
14:41:42 [INFO] [RandomSpawn] (DEBUG): DisconnectListener: Ev.. is removed from the deadlist.
14:41:42 [SEVERE] Could not pass event org.bukkit.event.player.PlayerQuitEvent to RandomSpawn
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1026)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:460)
        at net.minecraft.server.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:176)
        at net.minecraft.server.NetServerHandler.disconnect(NetServerHandler.java:141)
        at net.minecraft.server.NetLoginHandler.b(NetLoginHandler.java:169)
        at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:45)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:61)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:543)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1024)
        ... 10 more
Caused by: java.lang.NullPointerException
        at me.Josvth.RandomSpawn.Listeners.DisconnectListener.onPlayerDisconnect(DisconnectListener.java:26)
        ... 15 more
14:41:42 [INFO] [RandomSpawn] (DEBUG): Task 135608 : Chosing spawn.
14:41:42 [INFO] [RandomSpawn] (DEBUG): Task 135608 : Random Location found: Location{world=CraftWorld{name=world},x=-6835.5,y=64.0,z=-3225.5,pitch=0.0,yaw=0.0}
14:41:42 [INFO] [RandomSpawn] (DEBUG): Task 135608 : Generating spawn.
14:41:45 [INFO] [RandomSpawn] (DEBUG): Task 135608 : Ev.. is removed from the deadlist.
14:41:45 [INFO] [RandomSpawn] (DEBUG): Task 135608 : Ev.. is spawned at: -6835.5,64.0,-3225.5
14:41:45 [INFO] [RandomSpawn] (DEBUG): Task 135608 : Finished! (3357ms)
14:41:45 [INFO] [RandomSpawn] (DEBUG): Task 135608 : 441 chunks processed.
14:41:45 [INFO] [RandomSpawn] (DEBUG): Task 135608 : 1 chunks skipped.
14:41:45 [INFO] [RandomSpawn] (DEBUG): Task 135608 : 1 random location tries.
14:41:48 [INFO] [Hardcore 2.0] CraftPlayer{name=Ev..} is trying to log in.
14:41:48 [INFO] Ev.. [] logged in with entity id 110523 at ([world] 193.0, 10000.0, 64.0)
```

**Comment by mushroomhostage** [comment]
Updated to latest Random Spawn v1.8 on 1.2.3, to see if still reproduces.

**Comment by mushroomhostage** [comment]
Seems to be working well on ExpHC 1.2.3.
