### ISSUE TITLE
PlasticCraft cannot craft wood flour, conflicts with Mo' Food's bowls

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#2]
There is a crafting recipe conflict between [PlasticCraft](http://www.minecraftforum.net/topic/119361-110-tehkrushs-mods-all-mods-updated-and-plasticcraft-smp/#plastic) and [Mo' Foods and Crops](http://www.minecraftforum.net/topic/781133-11smpmo-foods-and-crops/). 

PlasticCraft's [wood flour](http://timefire.webs.com/PlasticCraft%20Recipes.html) is made using "1x Wood Plank = 4x Wood Flour", and is used in "1x Wood Flour + 1x Mould + (either 1x Egg, or 1x Bonemeal, or 1x Gelatin) = 1x Mould Full", which is in turn used in "Smelt 1x Mould Full = 3x PlasticBall", which is the basis for all plastic items. 

Mo' Food and Crops also uses 1x Wood Plank, for making 2 wooden plates. It overrides PlasticCraft, which is a pretty serious problem because wood flour is an important basic ingredient. Most PlasticCraft recipes are inaccessible as a result.

**Comment by mushroomhostage** [comment]
Probably best fixed by changing Mo' Food's recipe. Could do this as a server plugin, no mods required. 

Easy enough to write a new plugin to add the recipe, but would be better to configure an existing plugin, if possible. This one looks promising: http://dev.bukkit.org/server-mods/cookbook/

**Comment by mushroomhostage** [comment]
Workaround in the meantime: use Crafting Table II. It shows both Wood Flour and Dish.

**Comment by mushroomhostage** [comment]
[CookBook](http://dev.bukkit.org/server-mods/cookbook/) 1.0.1 for looks promising, but its for CB 1.1-R7. Latest modded CraftBukkit 1.1 is R4, so it fails:

```
21:44:12 [SEVERE] Error occurred while enabling Cookbook v1.0.1 (Is it up to date?): org.bukkit.Server.resetRecipes()V
java.lang.NoSuchMethodError: org.bukkit.Server.resetRecipes()V
at ca.celticminstrel.cookbook.Cookbook.resetOrClear(Cookbook.java:490)
at ca.celticminstrel.cookbook.Cookbook.loadRecipes(Cookbook.java:114)
at ca.celticminstrel.cookbook.Cookbook.onEnable(Cookbook.java:68)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:380)
at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:200)
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:183)
at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:360)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:347)
at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:178)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:411)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
```

There is new recipe API past 1.1-R4 for removing recipes, which explains this crash.

**Comment by mushroomhostage** [comment]
Tried to override in a plugin:

```
    ShapelessRecipe dishRecipe = new ShapelessRecipe(new ItemStack(ID_DISH, 2));
    dishRecipe.addIngredient(Material.getMaterial(ID_CLAY_BLOCK));

    ShapelessRecipe flourRecipe = new ShapelessRecipe(new ItemStack(ID_WOOD_FLOUR, 1));
    flourRecipe.addIngredient(Material.getMaterial(ID_PLANK));

    Bukkit.addRecipe(dishRecipe);
    Bukkit.addRecipe(flourRecipe);
```

The new dish recipe is added, but planks still craft dishes, not wood flour.

**Comment by mushroomhostage** [comment]
Remove recipe with [RecipeRepo](http://forums.bukkit.org/threads/admin-sec-reciperepo-v0-0-3-%E2%80%93-prevent-unwanted-recipes-1-0-1-r1.53461/)?

**Comment by mushroomhostage** [comment]
```
final int ID_WOOD_FLOUR = 1006;     // PlasticCraft
final int ID_PLANK = 5;             // vanilla
final int ID_CLAY_BLOCK = 82;       // vanilla
final int ID_DISH = 3704;           // Mo' Food and Crops
```

**Comment by mushroomhostage** [comment]
Even though its for 1.0.1, [RecipeRepo](http://forums.bukkit.org/threads/admin-sec-reciperepo-v0-0-3-%E2%80%93-prevent-unwanted-recipes-1-0-1-r1.53461/) still works on 1.1-R4. To remove dish recipe:

$ cat plugins/RecipeRepo/blockedrecipes.yml 
3704

now planks craft into wood flour (after briefly flashing into a dish, interestingly) – but I can't add my own clay -> dish recipe, since RecipeRepo blocks it, too.

**Comment by mushroomhostage** [comment]
Fixed by adding "softdepend: [RecipeRepo]" to recipe-adding plugin (BugTest1), so it loads after the recipes are removed.

commit 19849a6c291052641e47ae859be2b15121381e6c
Date:   Mon Mar 12 21:10:08 2012 -0700

```
Add clay block -> dish recipe for Mo' Food and Crops, works with RecipeRepo to remove the plank->dish recipe so plank crafts to wood flour for PlasticCraft. Fixes https://github.com/mushroomhostage/exphc/issues/2
```

**Comment by mushroomhostage** [comment]
Deployed changes on exphc, works great. A curious side-effect to note: Crafting Table II can still craft planks->dishes. Good side-effect, since it preserves the original recipe, if you want to access it (keeping in the balance of the original modders intentions).
