### ISSUE TITLE
Could not pass event EntityDamageEvent to EnchantMore

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#20]
On 1.2.3, EnchantMore periodically chokes on the EntityDamageEvent with an NPE:

```
22:43:58 [SEVERE] Could not pass event EntityDamageEvent to EnchantMore
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:441)
    at net.minecraft.server.EntityLiving.a(EntityLiving.java:829)
    at net.minecraft.server.EntityHuman.a(EntityHuman.java:1185)
    at net.minecraft.server.Entity.a(Entity.java:711)
    at net.minecraft.server.EntityPlayer.b(EntityPlayer.java:472)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:419)
    at net.minecraft.server.Packet10Flying.handle(SourceFile:126)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:234)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:118)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:557)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:455)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.NullPointerException
    at me.exphc.EnchantMore.EnchantMoreListener.hasEnch(EnchantMore.java:154)
    at me.exphc.EnchantMore.EnchantMoreListener.onPlayerDamaged(EnchantMore.java:2456)
    at me.exphc.EnchantMore.EnchantMoreListener.onEntityDamage(EnchantMore.java:2517)
    at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
    ... 14 more
```

Worked on 1.1, needs to be updated for new API in 1.2.3.

**Comment by mushroomhostage** [comment]
Fixed in EnchantMore 1.0.
