### ISSUE TITLE
Remove ear trumpet crafting workaround in ExphcTweaks

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#21]
For 1.1-R4, the enchantments lost on the ear trumpet crafting recipe was worked around in #17 by using a shapeless recipe bypassing the Bukkit API. Now that it is fixed in 1.2.3, this workaround in ExphcTweaks should be removed. Not only is it no longer needed it also causes errors:

```
java.lang.NoSuchMethodError: org.bukkit.inventory.ShapelessRecipe.getIngredientList()Ljava/util/ArrayList;
    at me.exphc.ExphcTweaks.ExphcTweaks.addRecipe602(ExphcTweaks.java:86)
    at me.exphc.ExphcTweaks.ExphcTweaks.fixRealisticChat_Crafting(ExphcTweaks.java:70)
    at me.exphc.ExphcTweaks.ExphcTweaks.onEnable(ExphcTweaks.java:47)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:363)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:376)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:363)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:189)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
```

**Comment by mushroomhostage** [comment]
Removed lots of workarounds in https://github.com/mushroomhostage/ExphcTweaks/commit/fbdfd49c2ecc2899854f58541a81276a32bdb6e4
