### ISSUE TITLE
Crash when viewing IC2 recipes

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#25]
Not Enough Items 1.2.0 crashes Minecraft whenever you view any recipe from IndustrialCraft^2.

**Comment by mushroomhostage** [comment]
Well-known problem author has fixed for 1.2.5. 

Meanwhile crashes can be avoided by downgrading to [NotEnoughItems-Client 1.1.3.zip](http://www.chickenbones.craftsaddle.org/Files/NEI/NotEnoughItems-Client%201.1.3.zip), but then IC2 recipes are not available.

ChickenBones published a hotfix in #redpower for [NotEnoughItems-Client 1.2.0.zip](http://www.chickenbones.craftsaddle.org/Files/NEI/NotEnoughItems-Client%201.2.0.zip): [IC2 1.8.1-NEI 1.1.3 Hotfix.zip](http://www.chickenbones.craftsaddle.org/Files/NEI/IC2%201.8.1-NEI%201.1.3%20Hotfix%20.zip), it works better but I still get a 100% reproducible crash when viewing the uses of Iron Dust:

```
ava.lang.ArrayIndexOutOfBoundsException: -3
    at java.util.ArrayList.get(ArrayList.java:324)
    at codechicken.nei.FurnaceRecipeHandler$SmeltingPair.getOtherStacks(FurnaceRecipeHandler.java:56)
    at codechicken.nei.TemplateRecipeHandler.getOtherStacks(TemplateRecipeHandler.java:238)
    at codechicken.nei.GuiRecipe.refreshSlots(GuiRecipe.java:191)
    at codechicken.nei.GuiRecipe.refreshPage(GuiRecipe.java:166)
    at codechicken.nei.GuiRecipe.c(GuiRecipe.java:51)
    at vl.a(SourceFile:91)
    at fy.a(GuiContainer.java:60)
    at net.minecraft.client.Minecraft.a(Minecraft.java:635)
    at fy.containerKeyPress(GuiContainer.java:356)
    at fy.a(GuiContainer.java:331)
    at vl.j(SourceFile:130)
    at vl.i(SourceFile:108)
    at fy.i(GuiContainer.java:421)
    at net.minecraft.client.Minecraft.k(Minecraft.java:1584)
    at net.minecraft.client.Minecraft.x(Minecraft.java:842)
    at net.minecraft.client.Minecraft.run(Minecraft.java:747)
    at java.lang.Thread.run(Thread.java:680)
```

but macerator recipes and copper cables still work.. better than nothing I guess, but sticking on NEI 1.1.3 for now. Can always use http://wiki.industrial-craft.net/ to view the IC^2 recipes if needed, and NEI for 1.2.5 will have a proper fix.
