### ISSUE TITLE
WRCBE 1.2.1 server crash NPE in RedstoneEtherAddonManager.getPlayerInfo(RedstoneEtherAddonManager.java:47)

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#42]
Player attempted to test his nuclear reactor failsafe, via a Wireless Redstone Chicken Bones edition transmitter, crashed server with:

20:34:59 [SEVERE] java.lang.NullPointerException
20:34:59 [SEVERE]       at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.getPlayerInfo(RedstoneEtherAddonManager.java:47)

Full log at:

https://gist.github.com/2860873

**Comment by mushroomhostage** [comment]
May be specific to something with how I have other mods with fake players (Forestry, RedPower, Buildcraft at least). Downloading a copy of the world to reproduce on a test server.

**Comment by mushroomhostage** [comment]
Attempted to repro on test server with copy of world, was unable. Charged battery, powered the remote thermal sensor, put uranium cells in the reactor. The industrial alarm signaled, with no crash. Need to figure out how WRCBE fit in here.

**Comment by mushroomhostage** [comment]
```
2012-06-04 17:21:00 [SEVERE] java.lang.NullPointerException
2012-06-04 17:21:00 [SEVERE]    at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.getPlayerInfo(RedstoneEtherAddonManager.java:47)
2012-06-04 17:21:00 [SEVERE]    at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.isRemoteOn(RedstoneEtherAddonManager.java:52)
2012-06-04 17:21:00 [SEVERE]    at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.tickTriangs(RedstoneEtherAddonManager.java:316)
2012-06-04 17:21:00 [SEVERE]    at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.onTick(RedstoneEtherAddonManager.java:557)
2012-06-04 17:21:00 [SEVERE]    at net.minecraft.server.mod_WirelessRedstoneAddons.onTickInGame(mod_WirelessRedstoneAddons.java:41)
2012-06-04 17:21:00 [SEVERE]    at cpw.mods.fml.server.ModLoaderModContainer.tickStart(ModLoaderModContainer.java:285)
2012-06-04 17:21:00 [SEVERE]    at cpw.mods.fml.common.FMLCommonHandler.gameTickStart(FMLCommonHandler.java:77)
2012-06-04 17:21:00 [SEVERE]    at cpw.mods.fml.server.FMLBukkitHandler.onPreTick(FMLBukkitHandler.java:129)
2012-06-04 17:21:00 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:494)
2012-06-04 17:21:00 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:453)
2012-06-04 17:21:00 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
2012-06-04 17:21:00 [SEVERE] Unexpected exception
java.lang.NullPointerException
        at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.getPlayerInfo(RedstoneEtherAddonManager.java:47)
        at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.isRemoteOn(RedstoneEtherAddonManager.java:52)
        at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.tickTriangs(RedstoneEtherAddonManager.java:316)
        at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.onTick(RedstoneEtherAddonManager.java:557)
        at net.minecraft.server.mod_WirelessRedstoneAddons.onTickInGame(mod_WirelessRedstoneAddons.java:41)
        at cpw.mods.fml.server.ModLoaderModContainer.tickStart(ModLoaderModContainer.java:285)
        at cpw.mods.fml.common.FMLCommonHandler.gameTickStart(FMLCommonHandler.java:77)
        at cpw.mods.fml.server.FMLBukkitHandler.onPreTick(FMLBukkitHandler.java:129)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:494)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:453)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
2012-06-04 17:32:30 [INFO] Read timed out
2012-06-04 17:34:13 [INFO] Connection reset
2012-06-04 17:36:31 [INFO] Connection reset
2012-06-04 17:47:30 [INFO] Read timed out
2012-06-04 18:32:38 [INFO] Read timed out
2012-06-04 18:52:39 [INFO] Read timed out
2012-06-04 19:33:16 [SEVERE] java.io.IOException: Bad packet id 71
2012-06-04 19:33:16 [SEVERE]    at net.minecraft.server.Packet.a(Packet.java:75)
2012-06-04 19:33:16 [SEVERE]    at net.minecraft.server.NetworkManager.h(NetworkManager.java:152)
2012-06-04 19:33:16 [SEVERE]    at net.minecraft.server.NetworkManager.c(NetworkManager.java:273)
2012-06-04 19:33:16 [SEVERE]    at net.minecraft.server.NetworkReaderThread.run(SourceFile:76)
2012-06-04 20:03:19 [INFO] Read timed out
```

**Comment by mushroomhostage** [comment]
Need more information to repro, or test further. Something to do with triangulation and remotes. 

Acquired copy of world before the crash, player was standing in front of CASUC nuclear reactor, did not have any wireless redstone equipment in hand. Everything is running smoothly and stable. However the crash may have rolled back so this is probably not accurate. The IC2 Nuclear Control alarm is wired to a WRCBE wireless transmitter. Going to try to trip it.

**Comment by mushroomhostage** [comment]
Tripped the alarm, transmitted on frequency 1. No crash. Tuned remote to 1, able to send signal. Added a wireless receiver to test. Have not yet found where the receiver was (if any).

**Comment by mushroomhostage** [comment]
```
22:02:15 [SEVERE] java.lang.NullPointerException
22:02:15 [SEVERE]       at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.getPlayerInfo(RedstoneEtherAddonManager.java:47)
22:02:15 [SEVERE]       at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.isRemoteOn(RedstoneEtherAddonManager.java:52)
22:02:15 [SEVERE]       at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.tickTriangs(RedstoneEtherAddonManager.java:316)
22:02:15 [SEVERE]       at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.onTick(RedstoneEtherAddonManager.java:557)
22:02:15 [SEVERE]       at net.minecraft.server.mod_WirelessRedstoneAddons.onTickInGame(mod_WirelessRedstoneAddons.java:41)
22:02:15 [SEVERE]       at cpw.mods.fml.server.ModLoaderModContainer.tickStart(ModLoaderModContainer.java:285)
22:02:15 [SEVERE]       at cpw.mods.fml.common.FMLCommonHandler.gameTickStart(FMLCommonHandler.java:77)
22:02:15 [SEVERE]       at cpw.mods.fml.server.FMLBukkitHandler.onPreTick(FMLBukkitHandler.java:129)
22:02:15 [SEVERE]       at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:494)
22:02:15 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:453)
22:02:15 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
22:02:15 [SEVERE] Unexpected exception
java.lang.NullPointerException
        at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.getPlayerInfo(RedstoneEtherAddonManager.java:47)
        at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.isRemoteOn(RedstoneEtherAddonManager.java:52)
        at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.tickTriangs(RedstoneEtherAddonManager.java:316)
        at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.onTick(RedstoneEtherAddonManager.java:557)
        at net.minecraft.server.mod_WirelessRedstoneAddons.onTickInGame(mod_WirelessRedstoneAddons.java:41)
        at cpw.mods.fml.server.ModLoaderModContainer.tickStart(ModLoaderModContainer.java:285)
        at cpw.mods.fml.common.FMLCommonHandler.gameTickStart(FMLCommonHandler.java:77)
        at cpw.mods.fml.server.FMLBukkitHandler.onPreTick(FMLBukkitHandler.java:129)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:494)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:453)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
```

**Comment by mushroomhostage** [comment]
A few other servers seeing this, [firstdeathmaker](http://forums.technicpack.net/index.php?topic=12234.0) reported:

> If you use the Wireless Tracker on someone, and that player loggs off, the server crashes. It is definately Wireless Redstone.

(anyone using wireless trackers?)

**Comment by mushroomhostage** [comment]
Reported at http://www.mcportcentral.co.za/index.php?topic=2899.0 + to cpw on IRC

**Comment by mushroomhostage** [comment]
Regressed in 1.2.2.3r2.
https://gist.github.com/3102207

2012-07-12 14:33:55 [SEVERE] Unexpected exception
java.lang.NullPointerException
        at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.getPlayerInfo(RedstoneEtherAddonManager.java:47)
        at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.isRemoteOn(RedstoneEtherAddonManager.java:52)
        at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.tickTriangs(RedstoneEtherAddonManager.java:316)
        at codechicken.wirelessredstone.addons.RedstoneEtherAddonManager.onTick(RedstoneEtherAddonManager.java:557)
        at net.minecraft.server.mod_WirelessRedstoneAddons.onTickInGame(mod_WirelessRedstoneAddons.java:41)
        at net.minecraft.server.BaseMod.doTickInGame(BaseMod.java:34)
        at cpw.mods.fml.common.modloader.BaseModTicker.sendTick(BaseModTicker.java:95)
        at cpw.mods.fml.common.modloader.BaseModTicker.tickBaseMod(BaseModTicker.java:83)
        at cpw.mods.fml.common.modloader.BaseModTicker.tickEnd(BaseModTicker.java:55)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:185)
        at cpw.mods.fml.server.FMLBukkitHandler.onServerPostTick(FMLBukkitHandler.java:631)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:607)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

**Comment by mushroomhostage** [comment]
Reported again to cpw on IRC + updated http://www.mcportcentral.co.za/index.php?topic=2899.msg18117#msg18117. Trying with copious null checks.
