### ISSUE TITLE
QuickBench broken with IC2 v1.97

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#61]
QuickBench can't open with IC2 v1.97, due to internal changes (which worked with IC2 1.95b):

2012-07-10 15:27:26 [WARNING] Failed to reflect crafting manager: java.lang.IllegalArgumentException: No enum constant ic2.common.AdvRecipe.oreDictionaryIC2.dyeBlue, falling back
2012-07-10 15:27:26 [SEVERE] java.lang.IllegalArgumentException: No enum constant ic2.common.AdvRecipe.oreDictionaryIC2.dyeBlue
2012-07-10 15:27:26 [SEVERE]    at java.lang.Enum.valueOf(Unknown Source)
2012-07-10 15:27:26 [SEVERE]    at ic2.common.AdvRecipe$oreDictionaryIC2.valueOf(AdvRecipe.java:1)
2012-07-10 15:27:26 [SEVERE]    at ic2.common.AdvShapelessRecipe.toBukkitRecipe(AdvShapelessRecipe.java:215)
2012-07-10 15:27:26 [SEVERE]    at com.exphc.QuickBench.QuickBenchListener.bypassGetRecipesIterator(QuickBench.java:250)
2012-07-10 15:27:26 [SEVERE]    at com.exphc.QuickBench.QuickBenchListener.getRecipesIteratorX(QuickBench.java:185)
2012-07-10 15:27:26 [SEVERE]    at com.exphc.QuickBench.QuickBenchListener.precraft(QuickBench.java:149)
2012-07-10 15:27:26 [SEVERE]    at com.exphc.QuickBench.QuickBenchListener.onPlayerInteract(QuickBench.java:127)
2012-07-10 15:27:26 [SEVERE]    at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
2012-07-10 15:27:26 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-07-10 15:27:26 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2012-07-10 15:27:26 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
2012-07-10 15:27:26 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2012-07-10 15:27:26 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
2012-07-10 15:27:26 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467)
2012-07-10 15:27:26 [SEVERE]    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
2012-07-10 15:27:26 [SEVERE]    at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:302)
2012-07-10 15:27:26 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:647)
2012-07-10 15:27:26 [SEVERE]    at net.minecraft.server.Packet15Place.handle(SourceFile:39)
2012-07-10 15:27:26 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:234)
2012-07-10 15:27:26 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:119)
2012-07-10 15:27:26 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:83)
2012-07-10 15:27:26 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:579)
2012-07-10 15:27:26 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
2012-07-10 15:27:26 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
2012-07-10 15:27:26 [SEVERE] Could not pass event PlayerInteractEvent to QuickBench
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
        at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:302)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:647)
        at net.minecraft.server.Packet15Place.handle(SourceFile:39)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:234)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:119)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:83)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:579)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.IllegalArgumentException: No enum constant ic2.common.AdvRecipe.oreDictionaryIC2.dyeBlue
        at java.lang.Enum.valueOf(Unknown Source)
        at ic2.common.AdvRecipe$oreDictionaryIC2.valueOf(AdvRecipe.java:1)
        at ic2.common.AdvShapelessRecipe.toBukkitRecipe(AdvShapelessRecipe.java:215)
        at org.bukkit.craftbukkit.inventory.RecipeIterator.next(RecipeIterator.java:33)
        at org.bukkit.craftbukkit.inventory.RecipeIterator.next(RecipeIterator.java:12)
        at com.exphc.QuickBench.QuickBenchListener.precraft(QuickBench.java:156)
        at com.exphc.QuickBench.QuickBenchListener.onPlayerInteract(QuickBench.java:127)
        at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
        ... 13 more

**Comment by mushroomhostage** [comment]
Whoa.. industrialcraft2-1.97-mcpc1.2.5-r1.zip actually implements (or tries to) toBukkitRecipe(). May be a porting bug!

But probably should reduce further..

**Comment by mushroomhostage** [comment]
Able to reproduce with RecipeList

**Comment by mushroomhostage** [comment]
Reported to porter: http://www.mcportcentral.co.za/index.php?topic=1402.msg18073#msg18073
but may be able to workaround myself

**Comment by mushroomhostage** [comment]
muCkk says he'll fix. Meanwhile added workaround in QuickBench:

https://github.com/mushroomhostage/QuickBench/commit/5592a3c8fc80720b732fe3406cea045948ee4018 Add resilence to broken toBukkitRecipe() implementations
