### ISSUE TITLE
Server crash: Remote Toolkit: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#63]
Server crashed with:

Exception in thread "stderr" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.drdanick.McRKit.Wrapper$3.run(Wrapper.java:546)

**Comment by mushroomhostage** [comment]
Changed rtoolkit.sh args from '-Xms30M -XX:MaxPermSize=40M' to 'java -Xms40M' per author's recommendation. Hit a different error earlier today:

```
Exception in thread "stderr" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.nio.CharBuffer.wrap(Unknown Source)
        at sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
        at sun.nio.cs.StreamEncoder.write(Unknown Source)
        at java.io.OutputStreamWriter.write(Unknown Source)
        at java.io.BufferedWriter.flushBuffer(Unknown Source)
        at java.io.PrintStream.newLine(Unknown Source)
        at java.io.PrintStream.println(Unknown Source)
        at com.drdanick.McRKit.Wrapper$3.run(Wrapper.java:536)
Terminated
```

**Comment by mushroomhostage** [comment]
This crash is particularly bad since it is in the wrapper which is supposed to restart the server when it crashes. 

Maybe caused by https://github.com/mushroomhostage/exphc/issues/62 WRCBE: "[INFO] Sending Triang:" log spam?

Disabled that message, seeing if rtoolkit still crashes..

**Comment by mushroomhostage** [comment]
https://github.com/mushroomhostage/exphc/commit/53f859867bc1481e1436b4435e03621dbd51e617
Haven't seen crash since..
