### ISSUE TITLE
Server crash: java.lang.StackOverflowError at net.minecraft.server.NBTTagShort.clone(SourceFile:35)

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#64]
Server crashed today with:

2012-07-11 16:46:09 [SEVERE] java.lang.StackOverflowError
2012-07-11 16:46:09 [SEVERE]    at net.minecraft.server.NBTTagShort.clone(SourceFile:35)
2012-07-11 16:46:09 [SEVERE]    at net.minecraft.server.NBTTagCompound.clone(NBTTagCompound.java:181)
2012-07-11 16:46:09 [SEVERE]    at net.minecraft.server.ItemStack.cloneItemStack(ItemStack.java:227)
2012-07-11 16:46:09 [SEVERE]    at net.minecraft.server.Container.clickItem(Container.java:171)
2012-07-11 16:46:09 [SEVERE]    at net.minecraft.server.Container.b(Container.java:263)
2012-07-11 16:46:09 [SEVERE]    at net.minecraft.server.Container.clickItem(Container.java:175)
2012-07-11 16:46:09 [SEVERE]    at net.minecraft.server.Container.b(Container.java:263)
..repeating about 2000 times..
        at net.minecraft.server.Container.clickItem(Container.java:175)
        at net.minecraft.server.Container.b(Container.java:263)
        at net.minecraft.server.Container.clickItem(Container.java:175)
2012-07-11 16:47:45 [INFO] Connection reset
2012-07-11 16:47:55 [INFO] Read timed out
2012-07-11 16:50:09 [INFO] Connection reset
2012-07-11 17:12:16 [INFO] Read timed out

**Comment by mushroomhostage** [comment]
Drobac reported: Ok this time when the server went kaput the only thing i did was make some diamonds out of UU in the project table and pick up all the quantum armor i had in my charging bench and the server went kaput while i was putting them in the personal safe

**Comment by mushroomhostage** [comment]
Similar "net.minecraft.server.Container.clickItem" reported at http://forums.bukkit.org/threads/severe-mysterious-bukkit-error.84437/ with no mods, isolated to http://dev.bukkit.org/server-mods/chestrestock/ plugin, but I'm not using it.

**Comment by mushroomhostage** [comment]
Same error reported April 8th, 2012, unsolved: http://www.minecraftforum.net/topic/1149305-weird-problem/

**Comment by mushroomhostage** [comment]
Not seen since..
