### ISSUE TITLE
java.lang.NoSuchMethodError: ack.cleanChunkBlockTileEntity(III)V

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#66]
threexone reported a client crash, twice: http://pastebin.com/vX7xqS3V and http://pastebin.com/vX7xqS3V

2012-07-11 22:57:40 [SEVERE] A critical error has occurred.
java.lang.NoSuchMethodError: ack.cleanChunkBlockTileEntity(III)V
        at xd.n(World.java:2094)
        at net.minecraft.client.Minecraft.k(Minecraft.java:1867)
        at net.minecraft.client.Minecraft.x(Minecraft.java:822)
        at net.minecraft.client.Minecraft.run(Minecraft.java:750)
        at java.lang.Thread.run(Unknown Source)

**Comment by mushroomhostage** [comment]
Could be an unauthorized client mod..

22:25:12 [INFO] [RealisticChat]() threexone -> threexone: it might be caused by world downloader, although i haven't used it yet

**Comment by mushroomhostage** [comment]
http://www.minecraftforum.net/topic/333322-world-downloader/
Why can't I just put your ZIP-file into my mods folder?
The mod that enables Minecraft to load other mods from this folder is called ModLoader.
ModLoader can only load mods that don't change any existing class files.
My mod needs to overwrite quite a few of them.

**Comment by mushroomhostage** [comment]
Definitely caused by a mod overwriting Forge..

patches/minecraft/net/minecraft/src/Chunk.java.patch
359:+    public void cleanChunkBlockTileEntity(int x, int y, int z) 

Player removed World Downloader. Closing.
