### ISSUE TITLE
Client crash when opening Teleport Pipes while using GraviSuite

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#69]
Wear a [Gravitation Suite](http://forum.industrial-craft.net/index.php?page=Thread&threadID=6915) (charged), tap F to turn it on, double-tap space to fly, then open an Item Teleport Pipe from [Additional Pipes for Buildcraft](http://www.minecraftforum.net/topic/856360-125bc2214-bc315rev213rev310-additional-pipes-for-buildcraft-teleport-pipes/). Client crashes immediately:

java.lang.IndexOutOfBoundsException: Index: 6, Size: 0
    at java.util.ArrayList.RangeCheck(ArrayList.java:547)
    at java.util.ArrayList.get(ArrayList.java:322)
    at dd.b(SourceFile:80)
    at dd.a(SourceFile:228)
    at adl.a(NetClientHandler.java:892)
    at fu.a(SourceFile:26)
    at lg.b(NetworkManager.java:343)
    at adl.b(NetClientHandler.java:71)
    at je.c(SourceFile:50)
    at net.minecraft.client.Minecraft.k(Minecraft.java:1873)
    at net.minecraft.client.Minecraft.x(Minecraft.java:822)
    at net.minecraft.client.Minecraft.run(Minecraft.java:750)
    at java.lang.Thread.run(Thread.java:680)
2012-07-14 10:42:55 [SEVERE] A critical error has occurred.
java.lang.IndexOutOfBoundsException: Index: 6, Size: 0
    at java.util.ArrayList.RangeCheck(ArrayList.java:547)
    at java.util.ArrayList.get(ArrayList.java:322)
    at dd.b(SourceFile:80)
    at dd.a(SourceFile:228)
    at adl.a(NetClientHandler.java:892)
    at fu.a(SourceFile:26)
    at lg.b(NetworkManager.java:343)
    at adl.b(NetClientHandler.java:71)
    at je.c(SourceFile:50)
    at net.minecraft.client.Minecraft.k(Minecraft.java:1873)
    at net.minecraft.client.Minecraft.x(Minecraft.java:822)
    at net.minecraft.client.Minecraft.run(Minecraft.java:750)
    at java.lang.Thread.run(Thread.java:680)

**Comment by mushroomhostage** [comment]
Crash does not occur in SSP. Occurs with Waterproof Teleport Pipe and Power Teleport Pipe as well. Doesn't occur while flying in creative mode, only with Gravitation Suite. Occurs with or without Smart Moving.

**Comment by mushroomhostage** [comment]
https://gist.github.com/3112345

**Comment by mushroomhostage** [comment]
Reported at http://forum.industrial-craft.net/index.php?page=Thread&postID=67347#post67347
Not pursuing further.. easy to just not fly when opening teleport pipes.

**Comment by mushroomhostage** [comment]
from http://forum.industrial-craft.net/index.php?page=Thread&postID=67971#post67971 "This is related to Additional Pipes, try using a pipe with a solar helmet and lappack/batpack on during the day. It'll do the same thing.

I'm pretty sure it's related to something in the Additional pipes GUI not liking it when the chestplate item is having something happen to it. In order to have it fixed, you'd have to have Additional Pipes updated to correct it. Good luck on that, as it appears to be abandoned."

**Comment by mushroomhostage** [comment]
New version of Additional Buildcraft Pipes at http://www.minecraftforum.net/topic/856360-125bc2214-bc315rev213rev310-additional-pipes-for-buildcraft-teleport-pipes/ is for Buildcraft 3, so I'm expecting this won't be fixed for Buildcraft 2

**Comment by mushroomhostage** [comment]
https://github.com/mushroomhostage/exphc/issues/99
