### ISSUE TITLE
Thermal Expansion - crescent hammer right-click configuration porting error

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#70]
Right-clicking a Thermal Expansion machine with a Crescent Hammer to open its Configuration GUI fails with 

12:17:42 [SEVERE] ALERT: SERIOUS BUKKIT PORTING ERROR. cofh.thermalexpansion.core.ContainerReconfigTool (false) or net.minecraft.server.ContainerPlayer (true) is a container that does not provide a valid player and inventory to bukkit.
The mod porter needs to provide a player through getPlayer() and an IInventory through getInventory().
You may encounter issues. File a bug with this message at mcportcentral.co.za, please.
java.lang.Throwable
        at net.minecraft.server.Container.transferTo(Container.java:40)
        at net.minecraft.server.NetServerHandler.handleContainerClose(NetServerHandler.java:1072)
        at net.minecraft.server.Packet101CloseWindow.handle(SourceFile:16)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:234)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:119)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:83)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:579)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

http://www.mcportcentral.co.za/index.php?topic=3281.msg18203#msg18203

**Comment by mushroomhostage** [comment]
cofh/thermalexpansion/core/ContainerReconfigTool.java should have the container methods, thought it should. getPlayer() is easy but getInventory() must return an IInventory yet TileReconfigRoot isn't an IInventory.
