### ISSUE TITLE
Some modded items cannot be enchanted

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#8]
New items added by mods cannot be enchanted successfully. Only vanilla items are enchantable.

Night vision goggles from [Mod:PlasticCraft](https://github.com/mushroomhostage/exphc/wiki/Mod:PlasticCraft) are supposed to be "enchantable" at the same level as leather armor according to [its recipes list](http://timefire.webs.com/PlasticCraft%20Recipes.html), but when placing the goggles in an enchantment table, no levels show up.

Knives (tested with diamond) from [Mod:Balkon's Weapon Mod](https://github.com/mushroomhostage/exphc/wiki/Mod:Balkon's-Weapon-Mod)
 can be placed in an enchantment table, and levels do show up, but clicking on a level disconnects the client with "Internal server error", with a stack trace shown on the console:

```
21:47:18 [WARNING] Failed to handle packet: java.lang.NullPointerException
java.lang.NullPointerException
    at net.minecraft.server.ContainerEnchantTable.a(ContainerEnchantTable.java:147)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1022)
    at net.minecraft.server.Packet108ButtonClick.handle(SourceFile:18)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:231)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:101)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:543)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
```

**Comment by mushroomhostage** [comment]
Bronze armor can be enchanted.

**Comment by mushroomhostage** [comment]
No longer have PlasticCraft, and Balkon's Weapon Mod v8.5 is available for 1.2.3 but not yet installed (other problem). Was this only buggy with those mods? Bronze armor is from IndustrialCraft^2.

**Comment by mushroomhostage** [comment]
Interesting discussion at http://minecraft-techworld.com/forum/index.php/topic/1112-drill-enchantment-solution-suggestion/ .

**Comment by mushroomhostage** [comment]
http://forums.bukkit.org/threads/req-custom-item-enchantments-via-enchanting-tables-formatted.64838/

**Comment by mushroomhostage** [comment]
The enchantability or lack thereof for each mod is by design.. IC^2 diamond drill enchanting would be interesting to investigate, but I'm closing this issue as won't fix in the meantime.
