### ISSUE TITLE
Update FreeTrade item database for rev5

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#81]
Update https://github.com/mushroomhostage/exphc/blob/master/1.2.5/plugins/FreeTrade/extra.yml for the new items added in the updated/new mods in rev5. 

Includes the new UsefulFood mod at least, but a couple other mods (Plugins for Forestry, TubeStuff, maybe more) also added new items.

**Comment by mushroomhostage** [comment]
```
20:34:00 [SEVERE] Error occurred while enabling FreeTrade v1 (Is it up to date?)
java.lang.RuntimeException: Unknown Track Spec = 28
    at railcraft.common.api.tracks.TrackRegistry.getTrackSpec(TrackRegistry.java:26)
    at railcraft.common.tracks.ItemTrack.a(ItemTrack.java:46)
    at me.exphc.FreeTrade.ItemQuery.scanNativeItems(FreeTrade.java:716)
    at me.exphc.FreeTrade.ItemQuery.loadConfig(FreeTrade.java:565)
    at me.exphc.FreeTrade.FreeTrade.loadConfig(FreeTrade.java:2251)
    at me.exphc.FreeTrade.FreeTrade.onEnable(FreeTrade.java:2220)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:386)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:264)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:246)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:377)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:364)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:198)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:428)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
```

**Comment by mushroomhostage** [comment]
> > > for a in d: print d,new[d]
> > > ... 
> > > set(['1378;4', '1378;5', '13368', '1379;2', '147;6', '451;0', '453;0', '1378;8', '147;7', '147;4', '147;5', '201;7', '191;3', '147;8', '147;9', '31264', '31261', '31263', '31262', '1378;2', '1378;3', '1379;9', '1378;1', '1378;6', '1378;7', '4037', '4036', '1379;3', '4038', '1379;1', '1378;9', '1379;7', '1379;6', '1379;5', '1379;4', '5308', '5309', '5306', '5307', '30108', '30107', '203;9', '5334', '5337', '5336', '1523;9', '4045', '5319', '5318', '1520;6', '5313', '5312', '5311', '5310', '5317', '11737', '5315', '5314', '11736', '30110', '4029', '204;8', '204;9', '204;6', '204;7', '204;4', '204;5', '4092;8', '204;3', '5326', '11735', '208;8', '208;9', '5322', '5323', '5320', '5321', '11744', '5328', '1527;9', '7273', '7274', '5327', '254;15', '5324', '5325', '253;25', '253;24', '253;27', '253;26', '209;4', '1524;3', '147;3', '201;8', '1524;7', '1524;6', '1524;5', '1524;4', '1524;9', '1524;8', '213;0', '213;1', '5331', '5330', '5333', '5332', '5335', '1523;5', '1523;6', '1523;7', '1523;8', '5338', '11740', '11741', '11742', '11743', '1527;8', '11745', '11746', '11747', '7265', '7264', '201;9', '1527;7', '7263', '5329', '215;4', '215;5', '215;6', '215;7', '215;0', '215;1', '215;2', '215;3', '215;8', '215;9', '7275', '1520;7', '11734', '1520;5', '1520;4', '11733', '11732', '1522;9', '1522;8', '11739', '11738', '1520;9', '1520;8', '198;8', '198;9', '198;6', '198;7', '198;4', '198;5', '198;3', '197;5', '197;4', '197;7', '197;6', '197;3', '197;2', '197;9', '197;8', '194;6', '11722', '11723', '11720', '11721', '199;9', '199;8', '11713', '11712', '1379;8', '11717', '11716', '11715', '11714', '11719', '11718'])
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > TypeError: unhashable type: 'set'
> > > for a in d: print a,new[a]
> > > ... 
> > > 1378;4 {'name': 'Candlex4'}
> > > 1378;5 {'name': 'Candlex5'}
> > > 13368 {'name': 'Chipsets'}
> > > 1379;2 {'name': 'Stumpx2'}
> > > 147;6 {'name': 'Tilexredrockx6'}
> > > 451;0 {'name': 'HayBall'}
> > > 453;0 {'name': 'ShocoCake'}
> > > 1378;8 {'name': 'Candlex8'}
> > > 147;7 {'name': 'Tilexredrockx7'}
> > > 147;4 {'name': 'Tilexredrockx4'}
> > > 147;5 {'name': 'Tilexredrockx5'}
> > > 201;7 {'name': 'Planterx7'}
> > > 191;3 {'name': 'Yourmumisfuckingugly'}
> > > 147;8 {'name': 'Tilexredrockx8'}
> > > 147;9 {'name': 'Tilexredrockx9'}
> > > 31264 {'name': 'ItemEnergyArrayLocationCard'}
> > > 31261 {'name': 'ItemTimeCard'}
> > > 31263 {'name': 'ItemEnergySensorLocationCard'}
> > > 31262 {'name': 'ItemEnergySensorKit'}
> > > 1378;2 {'name': 'Candlex2'}
> > > 1378;3 {'name': 'Candlex3'}
> > > 1379;9 {'name': 'Stumpx9'}
> > > 1378;1 {'name': 'Candlex1'}
> > > 1378;6 {'name': 'Candlex6'}
> > > 1378;7 {'name': 'Candlex7'}
> > > 4037 {'name': 'Horsearmordiamond'}
> > > 4036 {'name': 'Horsearmorgold'}
> > > 1379;3 {'name': 'Stumpx3'}
> > > 4038 {'name': 'Staffunicorn'}
> > > 1379;1 {'name': 'Stumpx1'}
> > > 1378;9 {'name': 'Candlex9'}
> > > 1379;7 {'name': 'Stumpx7'}
> > > 1379;6 {'name': 'Stumpx6'}
> > > 1379;5 {'name': 'Stumpx5'}
> > > 1379;4 {'name': 'Stumpx4'}
> > > 5308 {'name': 'PumpkinSoup'}
> > > 5309 {'name': 'Salad'}
> > > 5306 {'name': 'MagicFruitsalad'}
> > > 5307 {'name': 'FriedEgg'}
> > > 30108 {'name': 'Barrel'}
> > > 30107 {'name': 'id30107'}
> > > 203;9 {'name': 'Harvesterx9'}
> > > 5334 {'name': 'TrailMix'}
> > > 5337 {'name': 'RawMutton'}
> > > 5336 {'name': 'CookedMutton'}
> > > 1523;9 {'name': 'Tilexgrassx9'}
> > > 4045 {'name': 'Staffdiamond'}
> > > 5319 {'name': 'CaramelApple'}
> > > 5318 {'name': 'Caramel'}
> > > 1520;6 {'name': 'Tilexautumnleavesx6'}
> > > 5313 {'name': 'Sugarcube'}
> > > 5312 {'name': 'RoastedSeeds'}
> > > 5311 {'name': 'Fruitsalad'}
> > > 5310 {'name': 'Milk'}
> > > 5317 {'name': 'Chocolatecandy'}
> > > 11737 {'name': 'BootsFur'}
> > > 5315 {'name': 'Cheese'}
> > > 5314 {'name': 'Cocoa'}
> > > 11736 {'name': 'LegsFur'}
> > > 30110 {'name': 'id30110'}
> > > 4029 {'name': 'Horsearmormetal'}
> > > 204;8 {'name': 'Enginex8'}
> > > 204;9 {'name': 'Enginex9'}
> > > 204;6 {'name': 'Enginex6'}
> > > 204;7 {'name': 'Enginex7'}
> > > 204;4 {'name': 'Enginex4'}
> > > 204;5 {'name': 'Enginex5'}
> > > 4092;8 {'name': "'"}
> > > 204;3 {'name': 'Enginex3'}
> > > 5326 {'name': 'PorkchopSandwich'}
> > > 11735 {'name': 'HelmetFur'}
> > > 208;8 {'name': 'Millx8'}
> > > 208;9 {'name': 'Millx9'}
> > > 5322 {'name': 'RawMarshmallow'}
> > > 5323 {'name': 'Marshmallow'}
> > > 5320 {'name': 'Oatmeal'}
> > > 5321 {'name': 'Jelly'}
> > > 11744 {'name': 'Staff'}
> > > 5328 {'name': 'FishSandwich'}
> > > 1527;9 {'name': 'Tilexsaplingx9'}
> > > 7273 {'name': 'CreosoteCapsule'}
> > > 7274 {'name': 'ObsidianDust'}
> > > 5327 {'name': 'SteakSandwich'}
> > > 254;15 {'name': 'RockCrusher'}
> > > 5324 {'name': 'Icecream'}
> > > 5325 {'name': 'Breadslice'}
> > > 253;25 {'name': 'ReinforcedBoosterTrack'}
> > > 253;24 {'name': 'ReinforcedTrack'}
> > > 253;27 {'name': 'ReinforcedSwitchTrack'}
> > > 253;26 {'name': 'ReinforcedJunctionTrack'}
> > > 209;4 {'name': 'CrushedObsidian'}
> > > 1524;3 {'name': 'Tilexgreenleavesx3'}
> > > 147;3 {'name': 'Tilexredrockx3'}
> > > 201;8 {'name': 'Planterx8'}
> > > 1524;7 {'name': 'Tilexgreenleavesx7'}
> > > 1524;6 {'name': 'Tilexgreenleavesx6'}
> > > 1524;5 {'name': 'Tilexgreenleavesx5'}
> > > 1524;4 {'name': 'Tilexgreenleavesx4'}
> > > 1524;9 {'name': 'Tilexgreenleavesx9'}
> > > 1524;8 {'name': 'Tilexgreenleavesx8'}
> > > 213;0 {'name': 'ThatchedSlab'}
> > > 213;1 {'name': 'Test2'}
> > > 5331 {'name': 'AppleCake'}
> > > 5330 {'name': 'EggSandwich'}
> > > 5333 {'name': 'Bisquit'}
> > > 5332 {'name': 'ChocolateCake'}
> > > 5335 {'name': 'MagicCake'}
> > > 1523;5 {'name': 'Tilexgrassx5'}
> > > 1523;6 {'name': 'Tilexgrassx6'}
> > > 1523;7 {'name': 'Tilexgrassx7'}
> > > 1523;8 {'name': 'Tilexgrassx8'}
> > > 5338 {'name': 'MuttonSandwich'}
> > > 11740 {'name': 'Heartundead'}
> > > 11741 {'name': 'Ostrichmeat'}
> > > 11742 {'name': 'Ostrichcooked'}
> > > 11743 {'name': 'Unicorn'}
> > > 1527;8 {'name': 'Tilexsaplingx8'}
> > > 11745 {'name': 'Staffender'}
> > > 11746 {'name': 'Horsearmorcrystal'}
> > > 11747 {'name': 'Recordshuffle'}
> > > 7265 {'name': 'CreosoteOil'}
> > > 7264 {'name': 'CreosoteCan'}
> > > 201;9 {'name': 'Planterx9'}
> > > 1527;7 {'name': 'Tilexsaplingx7'}
> > > 7263 {'name': 'CreosoteBucket'}
> > > 5329 {'name': 'ChickenSandwich'}
> > > 215;4 {'name': 'FlowersxFernflowerY'}
> > > 215;5 {'name': 'FlowersxGerberaD'}
> > > 215;6 {'name': 'FlowersxHydrangea'}
> > > 215;7 {'name': 'FlowersxRedRover'}
> > > 215;0 {'name': 'FlowersxAlliumD'}
> > > 215;1 {'name': 'FlowersxBachelorsB'}
> > > 215;2 {'name': 'FlowersxBillyBs'}
> > > 215;3 {'name': 'FlowersxDelphiniumB'}
> > > 215;8 {'name': 'FlowersxSnapdragonM'}
> > > 215;9 {'name': 'FlowersxStarofBethlehem'}
> > > 7275 {'name': 'ReinforcedRail'}
> > > 1520;7 {'name': 'Tilexautumnleavesx7'}
> > > 11734 {'name': 'PlateFur'}
> > > 1520;5 {'name': 'Tilexautumnleavesx5'}
> > > 1520;4 {'name': 'Tilexautumnleavesx4'}
> > > 11733 {'name': 'Light'}
> > > 11732 {'name': 'Undead'}
> > > 1522;9 {'name': 'Tilexflowerx9'}
> > > 1522;8 {'name': 'Tilexflowerx8'}
> > > 11739 {'name': 'Heartfire'}
> > > 11738 {'name': 'Heartdarkness'}
> > > 1520;9 {'name': 'Tilexautumnleavesx9'}
> > > 1520;8 {'name': 'Tilexautumnleavesx8'}
> > > 198;8 {'name': 'Resourcex8'}
> > > 198;9 {'name': 'Resourcex9'}
> > > 198;6 {'name': 'Resourcex6'}
> > > 198;7 {'name': 'Resourcex7'}
> > > 198;4 {'name': 'Resourcex4'}
> > > 198;5 {'name': 'Resourcex5'}
> > > 198;3 {'name': 'Resourcex3'}
> > > 197;5 {'name': 'Soilx5'}
> > > 197;4 {'name': 'Soilx4'}
> > > 197;7 {'name': 'Soilx7'}
> > > 197;6 {'name': 'Soilx6'}
> > > 197;3 {'name': 'Soilx3'}
> > > 197;2 {'name': 'Soilx2'}
> > > 197;9 {'name': 'Soilx9'}
> > > 197;8 {'name': 'Soilx8'}
> > > 194;6 {'name': 'id194x6'}
> > > 11722 {'name': 'Darkness'}
> > > 11723 {'name': 'Nightmare'}
> > > 11720 {'name': 'Sharksword'}
> > > 11721 {'name': 'Key'}
> > > 199;9 {'name': 'OreCopperx9'}
> > > 199;8 {'name': 'OreCopperx8'}
> > > 11713 {'name': 'Omelet'}
> > > 11712 {'name': 'Fur'}
> > > 1379;8 {'name': 'Stumpx8'}
> > > 11717 {'name': 'Sai'}
> > > 11716 {'name': 'Nunchaku'}
> > > 11715 {'name': 'Turtlesoup'}
> > > 11714 {'name': 'Turtlemeat'}
> > > 11719 {'name': 'Katana'}
> > > 11718 {'name': 'Bo'}

**Comment by mushroomhostage** [comment]
https://github.com/mushroomhostage/exphc/commit/c076071a1d9563c25df43c7e7a5895bf44e1fe7a
Deployed, will take effect on next restart

**Comment by mushroomhostage** [comment]
Verified live
