### ISSUE TITLE
Teleport pipes GUI crashing

### ISSUE THREAD

**Issue by NewMilenium** [mushroomhostage/exphc#99]
Hello,

when I right click a teleport conductive pipe (so far, only one precise, i'm gonna test on another), Minecraft crashes and console shows this : 

setupTexture: "/net/minecraft/src/buildcraft/additionalpipes/gui/gui.png", id: 439
java.lang.IndexOutOfBoundsException: Index: 6, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at dd.b(SourceFile:80)
    at dd.a(SourceFile:228)
    at adl.a(NetClientHandler.java:892)
    at fu.a(SourceFile:26)
    at lg.b(NetworkManager.java:343)
    at adl.b(NetClientHandler.java:71)
    at je.c(SourceFile:50)
    at net.minecraft.client.Minecraft.k(Minecraft.java:1877)
    at net.minecraft.client.Minecraft.x(Minecraft.java:825)
    at net.minecraft.client.Minecraft.run(Minecraft.java:753)
    at java.lang.Thread.run(Unknown Source)
2012-08-25 16:38:46 [SEVERE] A critical error has occurred.
java.lang.IndexOutOfBoundsException: Index: 6, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at dd.b(SourceFile:80)
    at dd.a(SourceFile:228)
    at adl.a(NetClientHandler.java:892)
    at fu.a(SourceFile:26)
    at lg.b(NetworkManager.java:343)
    at adl.b(NetClientHandler.java:71)
    at je.c(SourceFile:50)
    at net.minecraft.client.Minecraft.k(Minecraft.java:1877)
    at net.minecraft.client.Minecraft.x(Minecraft.java:825)
    at net.minecraft.client.Minecraft.run(Minecraft.java:753)
    at java.lang.Thread.run(Unknown Source)

I wonder if this is because of the teleport pipe big number i set. i'm gonna destroy it and place it again.

edit after testing : 
Same error after destroying then replacing the power teleport pipe...
:-s

**Comment by mushroomhostage** [comment]
Were you flying in a gravitation suite? Looks like https://github.com/mushroomhostage/exphc/issues/69 (unfixed)

**Comment by NewMilenium** [comment]
No, i wasn't. But i had a gravitation suite on me.
Want me to retry with no gravi suite on me?

**Comment by mushroomhostage** [comment]
Yes, also if you could try with different /no armor that would help narrow down the problem.  http://forum.industrial-craft.net/index.php?page=Thread&postID=67971#post67971 says that "using a pipe with a solar helmet and lappack/batpack on during the day." will also crash.
